"aws_profile" = "my_profile"
"aws_key_pair_file" = "~/path/to/file.pem"
"aws_key_pair_name" = "my_keypair"
"tag_customer" = "AwesomeCustomer"
"tag_project" = "hab_win_ws"
"tag_dept" = "mydept"
"tag_contact" = "jmery"
"tag_ttl" = "8"
